# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleAdHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('host_pattern', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=30)),
                ('args', models.CharField(max_length=300)),
                ('host_file', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CloudManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
